services:
  instabox:
    container_name: instabox
    image: moh080203/instabox:latest
    networks:
      - vps-network
    volumes:
      - ./instabee.db:/app/resources/instabee.db
    env_file:
      - .env
